project_id = "yssqhlogdqdjmqwuvnkv"

[functions.gael-chat]
verify_jwt = true

[functions.seed-users]
verify_jwt = true

[functions.seed-drivers]
verify_jwt = false

[functions.ejg-chatbot]
verify_jwt = true
